vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer


    mappings:
        # Mapping pour l'image des articles
        articles_image:
            uri_prefix: /images/productimages
            upload_destination: "%kernel.project_dir%/public/images/productimages"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
    metadata:
        type: attribute